[package]
name = "optfield"
version = "0.3.0" # remember to update html_root_url and README
license = "MIT OR Apache-2.0"
description = "A macro that generates structs with optional fields"
repository = "https://github.com/roignpar/optfield"
readme = "README.md"
authors = ["Robert Ignat <robert.ignat91@gmail.com>"]
keywords = ["struct", "field", "optional", "option"]
categories = ["rust-patterns"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.27"
proc-macro2 = "1.0.56"

[dependencies.syn]
version = "2.0.15"
features = ["full", "extra-traits"]

[dev-dependencies]
paste = "1.0.12"
rstest = "0.12.0"

[dev-dependencies.serde]
version = "1.0.163"
features = ["derive"]
